apiVersion: v1
kind: ConfigMap
metadata:
  name: blue
  namespace: develop
data:
  nginx.conf: |
    server {
      listen 80;
      server_name localhost;
      location / {
        return 200 "Blue!\n";
      }
    }
