apiVersion: v1
kind: Service
metadata:
  name: nginx-blue
  namespace: develop
spec:
  selector:
    app: nginx-blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
