{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.conf.appName }}-hpa
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "epam.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-deployment" .Values.conf.appName | quote }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- if and .Values.autoscaling.behavior .Values.autoscaling.behavior.enabled }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.behavior.scaleUp.stabilizationWindowSeconds }}
      selectPolicy: {{ .Values.autoscaling.behavior.scaleUp.selectPolicy }}
      policies:
        - type: Percent
          value: {{ .Values.autoscaling.behavior.scaleUp.percentValue }}
          periodSeconds: {{ .Values.autoscaling.behavior.scaleUp.periodSeconds }}
        - type: Pods
          value: {{ .Values.autoscaling.behavior.scaleUp.podValue }}
          periodSeconds: {{ .Values.autoscaling.behavior.scaleUp.periodSeconds }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.behavior.scaleDown.stabilizationWindowSeconds }}
      selectPolicy: {{ .Values.autoscaling.behavior.scaleDown.selectPolicy }}
      policies:
        - type: Percent
          value: {{ .Values.autoscaling.behavior.scaleDown.percentValue }}
          periodSeconds: {{ .Values.autoscaling.behavior.scaleDown.periodSeconds }}
        - type: Pods
          value: {{ .Values.autoscaling.behavior.scaleDown.podValue }}
          periodSeconds: {{ .Values.autoscaling.behavior.scaleDown.periodSeconds }}
  {{- end }}
{{- end }}
